In [2]:
import pandas as pd 
from mlxtend.preprocessing import TransactionEncoder 
from mlxtend.frequent_patterns.fpgrowth import fpgrowth 
from mlxtend.frequent_patterns import association_rules

In [3]:
print("Enter the minimum support & confidence ") 
min_support = float(input("Enter minimum suppport : ")) 
print(min_support)
min_confidence = float(input("Enter the minimum confidence : ")) 
print(min_confidence)

Enter the minimum support & confidence
0.15
0.6

In [4]:
dataset = [['f', 'a', 'c', 'd', 'g', 'i', 'm','p'],
 ['a', 'b', 'c', 'f', 'l', 'm', 'o'],
 ['b', 'f', 'h', 'j', 'o', 'w'],
 ['b', 'c', 'k', 's', 'p'],
 ['a', 'f', 'c', 'e', 'l', 'p', 'm', 'n']]

In [5]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset) 
df = pd.DataFrame(te_ary, columns=te.columns_) 
df

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,s,w
0,True,False,True,True,False,True,True,False,True,False,False,False,True,False,False,True,False,False
1,True,True,True,False,False,True,False,False,False,False,False,True,True,False,True,False,False,False
2,False,True,False,False,False,True,False,True,False,True,False,False,False,False,True,False,False,True
3,False,True,True,False,False,False,False,False,False,False,True,False,False,False,False,True,True,False
4,True,False,True,False,True,True,False,False,False,False,False,True,True,True,False,True,False,False

In [6]:
print(f"\nFP tree with minimum support as {min_support*100}%\n")
pattern = fpgrowth(df, min_support=min_support, use_colnames=True, verbose=2)

FP tree with minimum support as 15.0%

18 itemset(s) from tree conditioned on items ()
0 itemset(s) from tree conditioned on items (c)
1 itemset(s) from tree conditioned on items (f)
3 itemset(s) from tree conditioned on items (a)
7 itemset(s) from tree conditioned on items (p)
5 itemset(s) from tree conditioned on items (m)
0 itemset(s) from tree conditioned on items (m, a)
1 itemset(s) from tree conditioned on items (m, f)
3 itemset(s) from tree conditioned on items (m, c)
7 itemset(s) from tree conditioned on items (m, p)
7 itemset(s) from tree conditioned on items (m, b)
31 itemset(s) from tree conditioned on items (g)
63 itemset(s) from tree conditioned on items (d)
127 itemset(s) from tree conditioned on items (i)
4 itemset(s) from tree conditioned on items (b)
0 itemset(s) from tree conditioned on items (b, f)
1 itemset(s) from tree conditioned on items (b, c)
3 itemset(s) from tree conditioned on items (b, a)
1 itemset(s) from tree conditioned on items (b, p)
31 itemset(s) from tree conditioned on items (o)
7 itemset(s) from tree conditioned on items (l)
0 itemset(s) from tree conditioned on items (l, m)
1 itemset(s) from tree conditioned on items (l, a)
3 itemset(s) from tree conditioned on items (l, f)
7 itemset(s) from tree conditioned on items (l, c)
15 itemset(s) from tree conditioned on items (l, o)
31 itemset(s) from tree conditioned on items (l, b)
15 itemset(s) from tree conditioned on items (l, p)
7 itemset(s) from tree conditioned on items (w)
15 itemset(s) from tree conditioned on items (h)
31 itemset(s) from tree conditioned on items (j)
7 itemset(s) from tree conditioned on items (s)
15 itemset(s) from tree conditioned on items (k)
63 itemset(s) from tree conditioned on items (e)
127 itemset(s) from tree conditioned on items (n)

In [7]:
print("\n\nThe association rules are as follows : ")
rules = association_rules(pattern, metric = "confidence", min_threshold = min_confidence) 
rules

The association rules are as follows :

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(f),(c),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
1,(c),(f),0.8,0.8,0.6,0.75,0.9375,-0.04,0.8,-0.25
2,(f),(a),0.8,0.6,0.6,0.75,1.2500,0.12,1.6,1.00
3,(a),(f),0.6,0.8,0.6,1.00,1.2500,0.12,inf,0.50
4,(c),(a),0.8,0.6,0.6,0.75,1.2500,0.12,1.6,1.00
...,...,...,...,...,...,...,...,...,...,...
9870,"(c, n)","(a, l, p, f, m, e)",0.2,0.2,0.2,1.00,5.0000,0.16,inf,1.00
9871,"(e, n)","(a, l, p, f, m, c)",0.2,0.2,0.2,1.00,5.0000,0.16,inf,1.00
9872,"(c, e)","(a, l, p, f, m, n)",0.2,0.2,0.2,1.00,5.0000,0.16,inf,1.00
9873,(n),"(a, l, p, f, m, c, e)",0.2,0.2,0.2,1.00,5.0000,0.16,inf,1.00
9874,(e),"(a, l, p, f, m, n, c)",0.2,0.2,0.2,1.00,5.0000,0.16,inf,1.00